# Generated by Django 4.1.3 on 2023-10-17 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category_text",
                    models.CharField(max_length=255, verbose_name="category_text"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "restaurant_text",
                    models.CharField(max_length=255, verbose_name="restaurant_text"),
                ),
                ("city", models.CharField(max_length=255, verbose_name="city")),
                ("location", models.CharField(max_length=255, verbose_name="location")),
                (
                    "restaurant_link",
                    models.CharField(max_length=255, verbose_name="restaurant_link"),
                ),
                (
                    "menu_link",
                    models.CharField(max_length=255, verbose_name="menu_link"),
                ),
                (
                    "price_rate",
                    models.CharField(max_length=255, verbose_name="price_rate"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="veggie.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state_text",
                    models.CharField(max_length=255, verbose_name="state_text"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "review_title",
                    models.CharField(max_length=255, verbose_name="review_title"),
                ),
                (
                    "review_description",
                    models.CharField(max_length=255, verbose_name="review_description"),
                ),
                (
                    "review_rate",
                    models.IntegerField(default=0, verbose_name="review_rate"),
                ),
                (
                    "price_rate",
                    models.CharField(max_length=50, verbose_name="price_rate"),
                ),
                (
                    "review_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="review_date"),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="veggie.restaurant",
                    ),
                ),
                (
                    "review_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="restaurant",
            name="state",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="veggie.state"
            ),
        ),
    ]
