# Generated by Django 4.2.6 on 2023-10-17 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("veggie", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="price_rate",
        ),
    ]
