# Generated by Django 4.1.3 on 2023-10-18 08:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("veggie", "0002_remove_review_price_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="review_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 10, 18, 8, 12, 50, 825793, tzinfo=datetime.timezone.utc
                ),
                verbose_name="review_date",
            ),
        ),
    ]
