# Generated by Django 4.1.3 on 2023-10-22 16:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("veggie", "0003_alter_review_review_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="image",
            field=models.URLField(
                default="https://www.analyticdesign.com/wp-content/uploads/2018/07/unnamed.gif",
                max_length=255,
                verbose_name="image",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="review_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="review_date"
            ),
        ),
    ]
