# Generated by Django 4.1.3 on 2023-10-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("veggie", "0004_restaurant_image_alter_review_review_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="image",
            field=models.URLField(max_length=255, verbose_name="image"),
        ),
    ]
