# Generated by Django 4.2.6 on 2023-11-09 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("veggie", "0005_alter_restaurant_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="category_text",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="category_text"
            ),
        ),
    ]
