# Generated by Django 4.2.6 on 2023-11-12 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veggie', '0006_alter_category_category_text'),
        ('veggie', '0006_bookmark'),
    ]

    operations = [
    ]
