# Generated by Django 4.1.5 on 2023-11-09 07:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('veggie', '0006_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='bookmark_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='bookmark_date'),
        ),
    ]
